SELECT l.LOCATION_ID, l.STREET_ADDRESS, l.CITY, l.STATE_PROVINCE, c.COUNTRY_NAME
FROM departments d 
LEFT JOIN
locations l
ON d.LOCATION_ID = l.LOCATION_ID
LEFT JOIN
countries c
ON l.COUNTRY_ID = c.COUNTRY_ID;